export default [
	'posthtml-load-plugins',
	'posthtml-standard-sequence',
	'posthtml-standard-config',
	'posthtml-cli',
	'posthtml-attrs-parser',
	'posthtml-parser',
	'posthtml-render',
	'postcss-cli',
	'postcss-value-parser',
	'babel-register',
	'gulp-cli',
	'babel-cli',
	'babel-eslint',
	'babel-register',
	'ava-codemods',
	'reshape-code-gen',
	'reshape-parser'
];
